// This file has been autogenerated from a class added in the UI designer.

using System;
using SelectionMenu.iOS;
using UIKit;

namespace SelectionSample
{
    public partial class SelectionTableViewCell : SelectionMenuTableViewCell<SampleItem>
    {
        public SelectionTableViewCell(IntPtr handle) : base(handle)
        {
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            SelectionStyle = UITableViewCellSelectionStyle.None;
            NameLabel.Text = "";
            CheckImage.Image = null;
        }

        protected override void BindItem(SampleItem selectionMenuItem)
        {
            NameLabel.Text = selectionMenuItem.Name;
        }

        protected override void OnItemSelected(bool isSelected)
        {
            CheckImage.Image = isSelected ? UIImage.CheckmarkImage : null;
        }
    }
}